export const reducerActions = {
  SET_SESSION: "SET_SESSION",
  SET_PROFILE: "SET_PROFILE",
  RELOAD_PROFILE: "RELOAD_PROFILE",
  STOP_APP_LOADING: "STOP_APP_LOADING",
  CONFIRM_PIN_SET: "CONFIRM_PIN_SET",
}